require:
  - rubocop-performance

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 34

Metrics/CyclomaticComplexity:
  Max: 14

Metrics/PerceivedComplexity:
  Max: 16

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/HashSlice:
  Enabled: false