#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)
require 'importer'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  KrakendOpenAPI::Importer.start(ARGV)
rescue StandardError => e
  warn "ERROR: #{e.message}"
  warn e.backtrace&.join("\n")
  exit 1
end
